### ISSUE TITLE
Integration of the CTU Relational Dataset Repository

### ISSUE THREAD

**Issue by jakubpeleska** [snap-stanford/relbench#264]
Hi guys :wave:,
foremost, thank you for the work done on this project and the effort of establishing the Relational Deep Learning subfield.

I am a PhD student at FEE CTU Prague under the mentorship of @GustikS. Currently, I am working on the [extension](https://github.com/jakubpeleska/ctu-relational-py) of the RelBench package to integrate the datasets of the [CTU Relational Dataset Repository](https://relational.fel.cvut.cz/). The package works directly with the SQL databases through SQLAlchemy and is intended to stay that way. Although this approach differs from the one used in the RelBench (and described in the contributing guidelines), I am curious if this is something that you would be interested in integrating into the RelBench or maybe adding as an optional dependency. Bear in mind that the package is still in development, intending to integrate all datasets from the repository with associated tasks.

Looking forward to your thoughts on the topic.

Jakub

**Comment by rishabh-ranjan** [comment]
Hi @jakubpeleska. Thanks for your interest in RelBench, and your efforts to integrate the CTU Relational Dataset Repository. This will be a valuable contribution to the community!

We are not too comfortable with working directly with SQL databases because of possible temporal leakage. However, we are happy to reconsider once your extension is complete.

In any case, we would like to point to your repo in our README so that visitors are aware. Please keep us updated on your progress, thanks!

**Comment by jakubpeleska** [comment]
@rishabh-ranjan Thanks for the reply and explanation. Having a link to the [extension](https://github.com/jakubpeleska/ctu-relational-py) in the README would be great. I will keep you posted on the updates.
